/**
 * Connector for Sanctions RESTful API
 * The purpose of this specification is to provide the details on how to integrate with the Connector for Sanctions RESTful API.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: am-integration-sysgroup@swift.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.io.swagger.api;

import java.util.ArrayList;
import java.util.List;

import org.apache.cxf.jaxrs.client.ClientConfiguration;
import org.apache.cxf.jaxrs.client.JAXRSClientFactory;
import org.apache.cxf.jaxrs.client.WebClient;
import org.junit.Before;
import org.junit.Test;

import com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider;
import com.io.swagger.model.CanonicalScreenMessage;

/**
 * API tests for ScreenmessageApi
 */
public class ScreenmessageApiTest {

	private ScreenmessageApi api;

	@Before
	public void setup() {
		JacksonJsonProvider provider = new JacksonJsonProvider();
		List<JacksonJsonProvider> providers = new ArrayList<>();
		providers.add(provider);

		api = JAXRSClientFactory.create("http://localhost:9090/v1", ScreenmessageApi.class, providers);
		org.apache.cxf.jaxrs.client.Client client = WebClient.client(api);

		ClientConfiguration config = WebClient.getConfig(client);
	}

	/**
	 * a XML canonical message in the body containing the message to screened
	 *
	 * This can only be done by the logged in user.
	 *
	 * @throws ApiException
	 *             if the Api call fails
	 */
	@Test
	public void screenmessageTest() {
		String body = null;
		api.screenmessage(body);

		// TODO: test validations

	}

}
